"use strict";
const tg=window.Telegram?.WebApp||null;
const key={lang:"lucky_boost_language",code:"lucky_boost_promo_code"};
const promos=["PLUGGSTAR","12VOLT","2026MDL","BOOST67","A7K2M9","BQ4X8L","C9D3P7","F2H6R1","G5J8T4","K3M7W2","N6P9Y5","Q4S2V8","T7U3Z6","X9C1B5","D8F4G2","H3J7K9","L5N1M6","P8R2S4","V6W9X3","Z2A5C7"];
const t={ru:{app:"Telegram Mini App",choose:"Выберите язык",chooseSub:"Выберите язык интерфейса.",homeTitle:"Повысить удачу",homeSub:"Запустите генератор и получите демонстрационный промокод.",start:"⚡ Сгенерировать удачу",loading:"Идёт подготовка…",wait:"Пожалуйста, подождите.",result:"Готово!",resultSub:"Ваш демонстрационный код создан.",copy:"📋 Скопировать код",copied:"✓ Скопировано",register:"🚀 Зарегистрироваться",again:"↻ Попробовать снова",change:"🌐 Изменить язык",demo:"Демонстрационная версия",steps:["Очищаем временные данные…","Проверяем настройки…","Анализируем параметры…","Подготавливаем промокод…","Завершаем подготовку…"]},en:{app:"Telegram Mini App",choose:"Choose a language",chooseSub:"Select the interface language.",homeTitle:"Boost your luck",homeSub:"Run the generator and get a demo promo code.",start:"⚡ Generate luck",loading:"Preparing…",wait:"Please wait.",result:"Ready!",resultSub:"Your demo code has been generated.",copy:"📋 Copy code",copied:"✓ Copied",register:"🚀 Register",again:"↻ Try again",change:"🌐 Change language",demo:"Demo version",steps:["Clearing temporary data…","Checking settings…","Analyzing parameters…","Preparing promo code…","Finishing preparation…"]},ro:{app:"Telegram Mini App",choose:"Alege limba",chooseSub:"Selectează limba interfeței.",homeTitle:"Îmbunătățește-ți norocul",homeSub:"Pornește generatorul și primește un cod promoțional demo.",start:"⚡ Generează noroc",loading:"Se pregătește…",wait:"Te rugăm să aștepți.",result:"Gata!",resultSub:"Codul tău demo a fost generat.",copy:"📋 Copiază codul",copied:"✓ Copiat",register:"🚀 Înregistrare",again:"↻ Încearcă din nou",change:"🌐 Schimbă limba",demo:"Versiune demo",steps:["Ștergem datele temporare…","Verificăm setările…","Analizăm parametrii…","Pregătim codul promoțional…","Finalizăm pregătirea…"]}};
const $=id=>document.getElementById(id);let lang=localStorage.getItem(key.lang),code=localStorage.getItem(key.code)||"",busy=false;
function haptic(type="light"){try{tg?.HapticFeedback?.impactOccurred(type)}catch{}}
function screen(id){["language","home","loading","result"].forEach(x=>$(x).classList.toggle("hidden",x!==id));if(tg?.BackButton){id==="language"?tg.BackButton.hide():tg.BackButton.show()}}
function apply(){const d=t[lang];document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=d[e.dataset.i18n]||"");$("start").textContent=d.start;$("copy").textContent=d.copy;$("again").textContent=d.again;$("change").textContent=d.change;$("changeResult").textContent=d.change}
function setLang(l){if(!t[l])return;lang=l;localStorage.setItem(key.lang,l);apply();haptic();code?($("code").textContent=code,screen("result")):screen("home")}
function start(){if(busy)return;busy=true;screen("loading");const d=t[lang],box=$("steps");box.innerHTML="";d.steps.forEach(s=>{const e=document.createElement("div");e.className="step";e.innerHTML='<span class="dot"></span><span></span>';e.lastChild.textContent=s;box.append(e)});$("bar").style.width="0";const steps=[...box.children];let i=0;function next(){if(i>=steps.length){code=promos[Math.floor(Math.random()*promos.length)];localStorage.setItem(key.code,code);$("code").textContent=code;busy=false;setTimeout(()=>screen("result"),400);return}const e=steps[i];e.classList.add("active");setTimeout(()=>{e.classList.replace("active","done");$("bar").style.width=((i+1)/steps.length*100)+"%";i++;next()},550)}next()}
async function copy(){if(!code)return;try{if(navigator.clipboard&&isSecureContext)await navigator.clipboard.writeText(code);else{const x=document.createElement("textarea");x.value=code;x.style.position="fixed";x.style.left="-9999px";document.body.append(x);x.select();document.execCommand("copy");x.remove()}$("copy").textContent=t[lang].copied;haptic()}catch{$("copy").textContent=code}setTimeout(()=>$("copy").textContent=t[lang].copy,1500)}
[...document.querySelectorAll("[data-lang]")].forEach(b=>b.onclick=()=>setLang(b.dataset.lang));$("start").onclick=start;$("copy").onclick=copy;$("again").onclick=()=>{localStorage.removeItem(key.code);code="";screen("home")};$("change").onclick=$("changeResult").onclick=()=>screen("language");tg?.ready();tg?.expand();tg?.BackButton?.onClick(()=>screen("home"));if(!t[lang]){lang="ru";apply();screen("language")}else{apply();code?($("code").textContent=code,screen("result")):screen("home")}